name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.5'
        cabal-version: '3.10.3.0'
    - name: "build main"
      run: cabal build homepage
    - name: "build cli"
      run: cabal build cli
